### ISSUE TITLE
Error login

### ISSUE THREAD

**Issue by Paolo296** [TimEnglart/BlackBoard-Course-Downloader#13]
## Expected behavior
to be able to log in

## Actual behavior
Login error, It asks me to retry even if my password and username are correct.

## Step to reproduce
+ python3 main.py
+ insert username and password
+ press c
+ search 'cattolica'
+ select 1

Here it fails login.

[here](https://github.com/TimEnglart/BlackBoard-Course-Downloader/files/5293623/dump.txt) the dump.json of the python3 debug.py

**Comment by TimEnglart** [comment]
Thanks for providing both the debug dump and the steps to reproduce your issue.

Looking at the dump and making API calls myself to your blackboard it appears that the backend path that this program uses to login is not functioning correctly.

If you could would it be possible to attempt to access your institute through the Mobile Blackboard App and reply to this issue about whether you are able to access your course data:
[Apple Store](https://apps.apple.com/us/app/blackboard/id950424861)
[Google Play](https://play.google.com/store/apps/details?id=com.blackboard.android.bbstudent)

Thanks

**Comment by Paolo296** [comment]
I use the app (android 11). It works fine and I'm able to log in without any problem.
To my description I want to add that trying with wrong password and wrong username seems to reproduce the same dump.json file

**Comment by kkl1974** [comment]
I am also facing this issue, my institution uses Microsoft 2 factor authentication though which I believe is the problem.

**Comment by ManishBhat** [comment]
I am facing the same issue as Paolo with the exact same steps. I have attached my dump.json for reference.
[dump.txt](https://github.com/TimEnglart/BlackBoard-Course-Downloader/files/6015746/dump.txt)

**Comment by TimEnglart** [comment]
> I am also facing this issue, my institution uses Microsoft 2 factor authentication though which I believe is the problem.

Hi @kkl1974,
Unfortunately the program currently doesn't have any integration with external login services and 2 factor authentication. I also do not have these login methods available to me so even if I had a endpoint I could use and documentation on how to implement these login methods I would not be able to test whether or not it resolves the issues that stem from these external services. Apologies but the only way for these login methods to work would be if someone was to fork and submit a PR.

**Comment by TimEnglart** [comment]
@ManishBhat,
Looking at your `dump.txt` there doesn't seem to be any issues with the client or the server with their responses unlike the original Issue.

If you are using an external login such as Google or Microsoft that may be the issue you are facing. 
But the server says that they are the incorrect details (either username or password). So you way just be entering them incorrectly.

I'll look into this to see if it is something to do with how the username and password are sent to the LMS.

**Comment by AnnaNihuang** [comment]
Hey, that didn't work D:

https://cdn.discordapp.com/attachments/820767241314369557/820778790186647563/unknown.png

**Comment by unaipuelles** [comment]
Hi, I had the same issue because my institution uses **Microsoft account to log into blackboard**. Applying #18 (and previously logged in my browser) to the code solved the issue and I downloaded successfully all the courses. One important thing is that **the user name has to be without @institution.com**, maybe is the same in your case.
I hope I help someone until the problem is fully solved.
If anybody has a question write me without any problem.

**Comment by kkl1974** [comment]
I have just gotten the program working with my institutions Blackboard and MS 2fa thanks to the instructions from @unaipuelles
and the merge requested fix made by @davenewham. I want to say thank you for this and thank you to TimEnglart for the program as I was downloading my course material manually, this project saved me so much time.

**Comment by TimEnglart** [comment]
Hi all,
Thanks for your testing and @davenewham's PR #18 hopefully most of your issues are resolved. Please move further conversation and issues to #19 so we can track login issues, share resolutions and make implementable issues accordingly

**Comment by ManishBhat** [comment]
Hi Tim,
Massive kudos 😀!Thanks to you, we have this awesome open-source tool.
Really grateful for the continued effort on your part.
Regards
Manish
