### ISSUE TITLE
Coding Error prevents this from working (screenshot attached)

### ISSUE THREAD

**Issue by AnnaNihuang** [TimEnglart/BlackBoard-Course-Downloader#17]
screenshot attached 

https://cdn.discordapp.com/attachments/214668723536134145/820792915205947402/unknown.png

**Comment by TimEnglart** [comment]
Hi @AnnaNihuang Thanks for Submitting this Issue.

After sending some requests to the endpoint used by your LMS it appears that logins need to go through their SSO instead of the method that this script uses.

I'll look into adding web scraping so that the program can use the SSO

**Comment by lacicloud** [comment]
Could we simply add an option that takes the session cookie from a browser and supplies that to the program instead of the username and password? It would be an easy solution to all the login issues. I have the same problem for TCD.

**Comment by TimEnglart** [comment]
That's probably the best course of action. I originally thought to scrape just so the program was autonomous (sort of) when attempting to login (but I guess you have to input your `username` and `password` anyways), which seems it wont be the case. When I tried to implement the scraping it introduced too many variables such as the browser and its version, the drivers required to run the browser supporting `x` version and the ridiculous amount of binaries that needed to be bundled to cover all browsers and operating systems.

I can or someone else can look into implementing: [browser_cookie3](https://github.com/borisbabic/browser_cookie3), [pycookiecheat](https://github.com/n8henrie/pycookiecheat) or a yet to be known package to get session data from the users browser and give it to the application.

**Comment by davenewham** [comment]
I implemented a rough and ready implementation of browser_cookie3 on my PR for my own use. However, I'm not sure if it would work for other institutes.

**Comment by TimEnglart** [comment]
Thanks to @davenewham and his PR #18 hopefully this issue is resolved. Feel free to comment if the issue still persists hopefully you can get the program running or comment on #19 so we can track login issues and make implementable issues accordingly 

Please Take a look at: [Issue #13's comments](https://github.com/TimEnglart/BlackBoard-Course-Downloader/issues/13#issuecomment-877870226) to see if this can also resolve any issues
